version: '3.8'

services:
  lvpnportal:
    image: sjc.vultrcr.com/lvpn/lvpnportal:latest
    container_name: lvpnportal
    restart: always
    expose:
      - "80"
    networks:
      - lvpn_network

  caddy:
    image: caddy:latest
    depends_on:
      - lvpnportal
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - lvpn_network
    volumes:
      - caddy_data:/data
      - ./etc/Caddyfile:/etc/caddy/Caddyfile

networks:
  lvpn_network:
    driver: bridge

volumes:
  caddy_data:
