name: VCR Docker Publish

on:
  schedule:
    - cron: '22 11 * * *'
  push:
    branches: [ "dev" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

    - name: Login to VCR
      run: |
        echo "${{ secrets.VCR_DOCKER_PASSWORD }}" | docker login -u "${{ secrets.VCR_DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker buildx create --use
        docker buildx inspect
        docker buildx build --platform linux/amd64 -t sjc.vultrcr.com/lvpn/lvpnportal:dev .
        docker buildx push docker push ssjc.vultrcr.com/lvpn/lvpnportal:dev
