name: VCR Docker Build Dev

on:
  schedule:
    - cron: '0 22 * * 1'
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

    - name: Login to VCR
      run: |
        echo "${{ secrets.VCR_DOCKER_PASSWORD }}" | docker login https://sjc.vultrcr.com/lvpn -u "${{ secrets.VCR_DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: |
        docker build --rm --no-cache -t  sjc.vultrcr.com/lvpn/lvpnportal-dev:latest .
        docker push sjc.vultrcr.com/lvpn/lvpnportal-dev:latest
