name: VCR Docker Build Dev

on:
  schedule:
    - cron: '0 22 * * 1'
  push:
    branches: [ "dev" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

    - name: Build Docker Image
      run: |
        docker build --rm --no-cache -t  sjc.vultrcr.com/lvpn/lvpnportal:dev .
        docker push sjc.vultrcr.com/lvpn/lvpnportal:dev
